osx_image: xcode8.3
language: objective-c
rvm:
- 2.2
before_install:
- openssl aes-256-cbc -K $encrypted_e14e58d8b5c1_key -iv $encrypted_e14e58d8b5c1_iv
  -in .autodeployment.sh.enc -out .autodeployment.sh -d
- chmod +x .autodeployment.sh
- . ./.autodeployment.sh
- bundle install
- pod install
script:
  - set -o pipefail && xcodebuild test -workspace Chambitas.xcworkspace -scheme Chambitas -sdk iphonesimulator10.3 -destination 'name=iPhone SE,OS=10.3' ONLY_ACTIVE_ARCH=NO | xcpretty
after_success:
- fastlane ios autodeploy