# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "Chambitas")
    upload_to_testflight
  end
end

desc "Auto deploy to TestFlight if merges pull request"
lane :autodeploy do
  if merges_pull_request
    # increment build number
    build_number = latest_testflight_build_number + 1
    increment_build_number(build_number: "#{build_number}")
    # create a new keychain
    password = SecureRandom.base64
    keychain_name = "fastlane"
    ENV["MATCH_KEYCHAIN_NAME"] = keychain_name
    ENV["MATCH_KEYCHAIN_PASSWORD"] = password

    create_keychain(
      name: keychain_name,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: password
    )

    # fetch provisioning profile
    match(
      type: "appstore",
      keychain_name: keychain_name,
      keychain_password: password,
      readonly: true
    )

    # build the app
    gym(scheme: "SchemeName", clean: true)

    # upload to TestFlight
    pilot
  end
end